In [34]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score

df = pd.read_csv("/Users/toiizumitarou/Documents/project/day5/sample_day2.csv")
df.head()

   patient_id  age  value        date  flag
0  patient_id  age  value        date  flag
1           1   34    5.4  2024-01-01     0
2           2   58    7.1  2024-01-02     1
3           3   45    6.1  2024-01-03     0
4           4   52    7.8  2024-01-04     1

In [36]:
#型確認（念のために）
df.dtypes

patient_id    object
age           object
value         object
date          object
flag          object
dtype: object

In [161]:
# 数値への型変換
df["patient_id"] = pd.to_numeric(df["patient_id"], errors="coerce")
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df["value"] = pd.to_numeric(df["value"], errors="coerce")
df["flag"] = pd.to_numeric(df["flag"], errors="coerce")

# 日付型へ変換
df["date"] = pd.to_datetime(df["date"], errors="coerce")

# 欠損を削る（素直に全部落とす）
df = df.dropna(subset=["patient_id", "age", "value", "flag", "date"])

# 年齢層カテゴリ
df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 40, 60, 120],
    labels=["young", "middle", "senior"]
)

# high_risk フラグ
df["high_risk"] = (df["value"] > 7.5).astype(int)

df.dtypes

patient_id           float64
age                  float64
value                float64
date          datetime64[ns]
flag                 float64
age_group           category
high_risk              int64
dtype: object

In [40]:
# モデル用データフレーム（カテゴリ列はダミー変数化）
df_model = pd.get_dummies(
    df[["age", "value", "high_risk", "age_group"]],
    drop_first=True
)

X = df_model
y = df["flag"]

X.head(), y.head()

(    age  value  high_risk  age_group_middle  age_group_senior
 1  34.0    5.4          0             False             False
 2  58.0    7.1          0              True             False
 3  45.0    6.1          0              True             False
 4  52.0    7.8          1              True             False
 5  41.0    5.9          0              True             False,
 1    0.0
 2    1.0
 3    0.0
 4    1.0
 5    0.0
 Name: flag, dtype: float64)

In [42]:
#分割
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [44]:
#学習
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [46]:
#評価(accuracy&AUC)
from sklearn.metrics import accuracy_score, roc_auc_score

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

acc = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)

print(f"Accuracy: {acc:.3f}, AUC: {auc:.3f}")

Accuracy: 0.950, AUC: 1.000

In [48]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score

In [50]:
df

     patient_id   age  value       date  flag age_group  high_risk
1           1.0  34.0    5.4 2024-01-01   0.0     young          0
2           2.0  58.0    7.1 2024-01-02   1.0    middle          0
3           3.0  45.0    6.1 2024-01-03   0.0    middle          0
4           4.0  52.0    7.8 2024-01-04   1.0    middle          1
5           5.0  41.0    5.9 2024-01-05   0.0    middle          0
..          ...   ...    ...        ...   ...       ...        ...
96         96.0  64.0    8.4 2024-04-05   1.0    senior          1
97         97.0  28.0    4.8 2024-04-06   0.0     young          0
98         98.0  54.0    7.6 2024-04-07   1.0    middle          1
99         99.0  37.0    5.7 2024-04-08   0.0     young          0
100       100.0  59.0    8.0 2024-04-09   1.0    middle          1

[100 rows x 7 columns]

In [52]:
# モデル用の特徴量データフレーム（ダミー変数化）
df_model = pd.get_dummies(
    df[["age", "value", "high_risk", "age_group"]],
    drop_first=True
)

X = df_model
y = df["flag"]

X.head(), y.head()

(    age  value  high_risk  age_group_middle  age_group_senior
 1  34.0    5.4          0             False             False
 2  58.0    7.1          0              True             False
 3  45.0    6.1          0              True             False
 4  52.0    7.8          1              True             False
 5  41.0    5.9          0              True             False,
 1    0.0
 2    1.0
 3    0.0
 4    1.0
 5    0.0
 Name: flag, dtype: float64)

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [57]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [59]:
from sklearn.metrics import accuracy_score, roc_auc_score

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

acc = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)

print(f"Accuracy: {acc:.3f}, AUC: {auc:.3f}")

Accuracy: 0.950, AUC: 1.000